### ISSUE TITLE
Cannot run interactive.py

### ISSUE THREAD

**Issue by blobsimulator** [openai/multiagent-particle-envs#12]
Hi.

I just cloned the repository and tried to run interactive.py, but got the following traceback:

>WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "bin/interactive.py", line 21, in <module>
    env = MultiAgentEnv(world, scenario.reset_world, scenario.reward, scenario.observation, info_callback=None, shared_viewer = False)
  File "/home/name/code/multiagent-particle-envs/bin/../multiagent/environment.py", line 68, in __init__
    self.observation_space.append(spaces.Box(low=-np.inf, high=+np.inf, shape=(obs_dim),))
  File "/usr/local/lib/python3.5/dist-packages/gym/spaces/box.py", line 33, in __init__
    Space.__init__(self, shape, dtype)
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 161, in __init__
    self.shape = None if shape is None else tuple(shape)
TypeError: 'int' object is not iterable

I have found that I can overcome this particular error if I change (in `environment.py row 68`)

> self.observation_space.append(spaces.Box(low=-np.inf, high=+np.inf, shape=(obs_dim),))

to

> self.observation_space.append(spaces.Box(low=-np.inf, high=+np.inf, shape=(obs_dim,)))

However, then I start getting a whole new bunch of errors.

Any clue as to what to I am doing wrong?

**Comment by nikunjparmar828** [comment]
@blobsimulator Can you please send those new errors.I did same change and my code is running well.

**Comment by blobsimulator** [comment]
>Traceback (most recent call last):
  File "bin/interactive.py", line 23, in <module>
    env.render()
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 110, in render
    raise NotImplementedError
NotImplementedError

Is there perhaps a directory issue going on now? Thanks a lot for helping out @nikunjparmar828

**Comment by ryan-lowe** [comment]
for some reason, the default scenario in interactive.py was not set. should be fixed now

**Comment by emanuelepesce** [comment]
I've just cloned and I still have the same issue with python 3. Any suggestions?

**Comment by ryan-lowe** [comment]
Could you post the error? It works for me when I clone and I'm using Python 3.5.4

**Comment by ryan-lowe** [comment]
or you mean it's the same error as blobsimulator was getting?

**Comment by watts4speed** [comment]
@ryan-lowe I see.  I'm using Python 3.5 loaded into a Pycharm-Env.  I'm on linux 16.04.  I'll look into switching to 3.5.4.  You might have nailed it.

**Comment by emanuelepesce** [comment]
Yes, same error on `bin/interactive.py --scenario simple.py`

`Traceback (most recent call last):
  File "bin/interactive.py", line 21, in <module>
    env = MultiAgentEnv(world, scenario.reset_world, scenario.reward, scenario.observation, info_callback=None, shared_viewer = False)
  File "/home/ep15/mylibs/multiagents-particle-envs_36/multiagent-particle-envs/bin/../multiagent/environment.py", line 68, in __init__
    self.observation_space.append(spaces.Box(low=-np.inf, high=+np.inf, shape=(obs_dim),))
  File "/home/ep15/anaconda2/envs/py364/lib/python3.6/site-packages/gym/spaces/box.py", line 33, in __init__
    Space.__init__(self, shape, dtype)
  File "/home/ep15/anaconda2/envs/py364/lib/python3.6/site-packages/gym/core.py", line 161, in __init__
    self.shape = None if shape is None else tuple(shape)
TypeError: 'int' object is not iterable`

It occur with python 3 (tested on 3.6.4 and 3.5) 
SO: Ubuntu 16.04

**Comment by ymolists** [comment]
i have the same issue in ubuntu17.10. i used virtualenv to create an env for both python2 and python3 and i still get the same error.

>(multiagent-particle-envs.000) ~/3rdp/apps/openai/multiagent-particle-envs$ ./bin/interactive.py --scenario simple.py
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "./bin/interactive.py", line 23, in <module>
    env.render()
  File "/data/3rdp/apps/openai/multiagent-particle-envs.000/local/lib/python2.7/site-packages/gym/core.py", line 111, in render
    raise NotImplementedError
NotImplementedError

**Comment by yakotaki** [comment]
@blobsimulator @ymolists
Try with gym version 0.9.5
I had same problem, changing gym helped.
