### ISSUE TITLE
Can't run interactive.py 

### ISSUE THREAD

**Issue by mvrozanti** [openai/multiagent-particle-envs#40]
```
agent 1 to agent 0: _   agent 2 to agent 0: _   agent 0 to agent 1: _   agent 2 to agent 1: _   agent 0 to agent 2: _   agent 1 to agent 2: _   
Traceback (most recent call last):
  File "./interactive.py", line 34, in <module>
    obs_n, reward_n, done_n, _ = env.step(act_n)
  File "/mnt/4ADE1465DE144C17/Programming/python/multiagent-particle-envs/bin/../multiagent/environment.py", line 94, in step
    reward_n.append(self._get_reward(agent))
  File "/mnt/4ADE1465DE144C17/Programming/python/multiagent-particle-envs/bin/../multiagent/environment.py", line 141, in _get_reward
    return self.reward_callback(agent, self.world)
  File "/mnt/4ADE1465DE144C17/Programming/python/multiagent-particle-envs/bin/../multiagent/scenarios/simple_crypto.py", line 96, in reward
    return self.adversary_reward(agent, world) if agent.adversary else self.agent_reward(agent, world)
  File "/mnt/4ADE1465DE144C17/Programming/python/multiagent-particle-envs/bin/../multiagent/scenarios/simple_crypto.py", line 120, in adversary_reward
    if not (agent.state.c == np.zeros(world.dim_c)).all():
AttributeError: 'bool' object has no attribute 'all'
```
```
$ pip list | grep "gym|numpy"

gym                      0.10.5
numpy                    1.14.5
numpy-stl                2.8.0

$ python -V

Python 3.6.0
```

`(a.state.c == np.zeros(world.dim_c)).all()`

Can anyone tell me what this means? 

Thanks

**Comment by AmulyaReddy99** [comment]
Try updating your gym to gym==0.14.0 version

**Comment by mvrozanti** [comment]
Thanks
