### ISSUE TITLE
Error when display simple_crypto

### ISSUE THREAD

**Issue by rical730** [openai/multiagent-particle-envs#61]
Python (3.5.4)
OpenAI gym (0.10.5)
tensorflow (1.8.0)
numpy (1.14.5)

maddpg code: https://github.com/openai/maddpg

I got an error when I run the maddpg code in the simple scene and display it
PS:  8 other environments can work

========================================
Step 1 : train and save model
$ python train.py --scenario simple_crypto

2020-01-22 17:46:58.755855: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Starting iterations...
steps: 24975, episodes: 1000, mean episode reward: -22.24953384943575, time: 26.487
steps: 49975, episodes: 2000, mean episode reward: -17.158019479170676, time: 43.373
steps: 74975, episodes: 3000, mean episode reward: -14.317337732475657, time: 43.159
steps: 99975, episodes: 4000, mean episode reward: -7.1827372802086815, time: 45.176

========================================
Step 2 : restore model and display
$ python train.py --scenario simple_crypto --display

2020-01-22 17:50:47.412262: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loading previous state...
Starting iterations...
agent 1 to agent 0: B   agent 2 to agent 0: C   agent 0 to agent 1: A   agent 2 to agent 1: C   agent 0 to agent 2: A   agent 1 to agent 2: B
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    train(arglist)
  File "train.py", line 170, in train
    env.render()
  File "/Users/likejiao/Documents/LKJDocument/Code/github/openai/multiagent-particle-envs/multiagent/environment.py", line 234, in render
    geom.set_color(*entity.color, alpha=0.5)
TypeError: set_color() got multiple values for argument 'alpha'

========================================
Is there something wrong with the simple_crypto scenario?

**Comment by Conquerer-yinn** [comment]
Hello, may I ask how you train the model? When I use "train.py" I can only train "simple" and everything else will give me an error.
